"""End-to-end link between label aggregation and the confirmation models.

Reviewer question this closes: the consensus simulation (consensus_sim.py) and
the classifier benchmark (confirm_models.py) were run separately, so it was not
shown whether the choice of aggregation rule matters for the downstream task.

Protocol, per category x split seed (0..4) x votes-per-item k in {3,5,7}:
  1. split exactly as confirm_models.py (stratified 80/20);
  2. replace the TRAINING labels with simulated crowd votes from the same
     mixed annotator population as consensus_sim.py (12 annotators: 40% expert,
     40% mediocre, 20% adversarial), k votes per item;
  3. aggregate with majority vote, the reliability-weighted rule (Eq. 2) and
     Dawid-Skene EM; also train on gold labels as an upper bound;
  4. train the unigram BoW and the character n-gram logistic regressions on
     each aggregated label set and score them on the CLEAN test labels.

The test labels are never noised. All data are synthetic.
Run:  python src/aggregation_to_training.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

import consensus_sim as cs
from make_synth import _categories

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "synth"
RESULTS_DIR = ROOT / "results"
SEEDS = [0, 1, 2, 3, 4]
K_VALUES = [3, 5, 7]

MODELS = {
    "Unigram BoW + LogReg": dict(binary=True),
    "Char n-gram(3-5) + LogReg": dict(binary=True, analyzer="char_wb",
                                      ngram_range=(3, 5)),
}


def dawid_skene_vec(votes, voters, n_ann, n_iter=50):
    """Vectorised binary Dawid-Skene; same model as consensus_sim._dawid_skene."""
    obs = (votes == 1).astype(int)
    n, k = obs.shape
    p1 = obs.mean(axis=1)
    T = np.stack([1 - p1, p1], axis=1)
    flat_a, flat_o = voters.ravel(), obs.ravel()
    for _ in range(n_iter):
        pi = np.ones((n_ann, 2, 2))
        Trep = np.repeat(T, k, axis=0)
        for c in (0, 1):
            np.add.at(pi[:, c, :], (flat_a, flat_o), Trep[:, c])
        pi /= pi.sum(axis=2, keepdims=True)
        prior = T.sum(axis=0) + 1.0
        prior /= prior.sum()
        logp = np.log(prior)[None, :].repeat(n, axis=0)
        for c in (0, 1):
            logp[:, c] += np.log(pi[voters, c, obs]).sum(axis=1)
        logp -= logp.max(axis=1, keepdims=True)
        newT = np.exp(logp)
        newT /= newT.sum(axis=1, keepdims=True)
        done = np.abs(newT - T).max() < 1e-6
        T = newT
        if done:
            break
    return (T[:, 1] > 0.5).astype(int)


def _train_eval(kw, X_tr, y_tr, X_te, y_te, seed):
    if len(set(y_tr)) < 2:
        return 0.0
    vec = CountVectorizer(**kw)
    clf = LogisticRegression(max_iter=1000, random_state=seed)
    clf.fit(vec.fit_transform(X_tr), y_tr)
    return f1_score(y_te, clf.predict(vec.transform(X_te)), zero_division=0)


def main() -> None:
    rows = []
    for ci, cfg in enumerate(_categories()):
        df = pd.read_parquet(DATA_DIR / f"{cfg.name}.parquet")
        texts, labels = df.text.tolist(), df.label.values
        for seed in SEEDS:
            X_tr, X_te, y_tr, y_te = train_test_split(
                texts, labels, test_size=0.2, stratify=labels, random_state=seed)
            y_tr = np.asarray(y_tr)
            for k in K_VALUES:
                rng = np.random.RandomState(100000 + 1000 * ci + 10 * seed + k)
                acc = cs._sample_accuracies(rng)
                votes, voters = cs._generate_votes(rng, y_tr, acc, k)
                label_sets = {
                    "Gold (upper bound)": y_tr,
                    "Majority": cs._majority(votes, voters, rng),
                    "Reliability-weighted": cs._reliability_weighted(votes, voters, rng),
                    "Dawid-Skene": dawid_skene_vec(votes, voters, cs.N_ANNOTATORS),
                }
                for agg, y_hat in label_sets.items():
                    for model, kw in MODELS.items():
                        rows.append({
                            "category": cfg.name, "seed": seed, "k": k,
                            "aggregator": agg, "model": model,
                            "train_label_accuracy": float((y_hat == y_tr).mean()),
                            "test_f1": _train_eval(kw, X_tr, y_hat, X_te, y_te, seed),
                        })
        print(f"  done {cfg.name}")
    out = pd.DataFrame(rows)
    RESULTS_DIR.mkdir(exist_ok=True)
    # Per-run rows are large; they are regenerated by `make audit` and not
    # committed. The summary below is what the paper reports (Table 3).
    out.to_csv(RESULTS_DIR / "aggregation_to_training.csv", index=False,
               float_format="%.6g")
    summary = (out.groupby(["model", "k", "aggregator"])
               .agg(train_label_accuracy=("train_label_accuracy", "mean"),
                    test_f1_mean=("test_f1", "mean"),
                    test_f1_sd=("test_f1", "std"))
               .reset_index())
    summary.to_csv(RESULTS_DIR / "aggregation_to_training_summary.csv",
                   index=False, float_format="%.6g")
    pd.set_option("display.width", 200)
    summ = (out.groupby(["model", "k", "aggregator"])
            [["train_label_accuracy", "test_f1"]]
            .agg(["mean", "std"]).round(4))
    print(summ.to_string())


if __name__ == "__main__":
    main()
